head_controller_node:
  ros__parameters:
    idle_move_min_interval: 10.0
    idle_move_max_interval: 20.0
    pan_limit: [-1.0, 1.0]
    tilt_limit: [-0.30, 0.0]
    tolerance: 0.001
    tracking_timeout: 5.0
    joint_group_name: "turret"
    pan_joint: "pan"
    tilt_joint: "tilt"
    tracking_topic: "/head_goal"
    profile_velocity: 2000
    profile_acceleration: 100