collision_monitor:
  ros__parameters:
    use_sim_time: False
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_raw"
    cmd_vel_out_topic: "cmd_vel"
    transform_tolerance: 0.1
    source_timeout: 2.0
    stop_pub_timeout: 0.5
    base_shift_correction: true
    polygons: ["SlowdownFair", "SlowdownNear"]
    observation_sources: ["laser_front", "laser_back", "camera_depth"]

    laser_front:
      topic: "/scan_1st"
      max_obstacle_height: 2.0
      clearing: True
      marking: True
    laser_back:
      topic: "/scan_2nd"
      max_obstacle_height: 2.0
      clearing: True
      marking: True
    camera_depth:
      topic: "/scan_camera"
      clearing: True
      marking: True
      min_obstacle_height: 0.1
      max_obstacle_height: 1.8

    SlowdownFair:
      type: "polygon"
      action_type: "slowdown"
      slowdown_ratio: 0.5 
      # Caja proyectada 1.2m hacia adelante y solo 0.5m de ancho.
      # [1.2, 0.25, 1.2, -0.25, 0.2, -0.25, 0.2, 0.25]
      points: [1.2, 0.25, 1.2, -0.25, 0.2, -0.25, 0.2, 0.25]
      min_points: 6
      visualize: true

    SlowdownNear:
      type: "polygon"
      action_type: "slowdown"
      slowdown_ratio: 0.2 
      # Caja proyectada 0.6m hacia adelante, un poco más estrecha
      points: [0.65, 0.25, 0.65, -0.25, 0.1, -0.25, 0.1, 0.25]
      min_points: 5
      visualize: true
