planner_server:
  ros__parameters:
    use_sim_time: False
    expected_planner_frequency: 2.0
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_smac_planner/SmacPlanner2D"
      tolerance: 0.20
      allow_unknown: true
      max_iterations: 1000000
      max_on_approach_iterations: 1500
      terminal_checking_interval: 4000
      max_planning_time: 1.0
      downsample_costmap: false
      downsampling_factor: 2
      cost_travel_multiplier: 10.0 # High - More priority to obstacle avoidance than path length
      use_final_approach_orientation: false


global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: False
      global_frame: "map"
      track_unknown_space: false
      robot_base_frame: "base_footprint"
      resolution: 0.01
      downsample_costmap: false

      footprint_padding: 0.005
      transform_tolerance: 0.2

      update_frequency: 2.0
      publish_frequency: 2.0

      footprint: "[[-0.30, -0.20], [-0.30, 0.20], [0.30, 0.20], [0.30, -0.20]]"
      
      plugins:
        - "static_layer"
        - "obstacle_layer"
        - "keepout_filter"
        - "inflation_layer"

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: true
        map_subscribe_transient_local: true
        subscribe_to_updates: false
        transform_tolerance: 0.2

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        footprint_clearing_enabled: true
        max_obstacle_height: 2.0
        combination_method: 1
        observation_sources: "laser_front laser_back"
        allow_unknown: true

        laser_front:
          topic: "/scan_1st"
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          observation_persistence: 0.5  

        laser_back:
          topic: "/scan_2nd"
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          observation_persistence: 0.5


      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: true
        filter_info_topic: "/costmap_filter_info"
        
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 2.0
        cost_scaling_factor: 7.0
        inflate_unknown: true
        inflate_around_unknown: true
      
      always_send_full_costmap: True

costmap_filter_info_server:
  ros__parameters:
    use_sim_time: False
    type: 0
    filter_info_topic: "/costmap_filter_info"
    mask_topic: "/keepout_filter_mask"
    base: 0.0
    multiplier: 1.0